### ISSUE TITLE
update view for /transactions route automatically

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#100]
currently we display following message if the page is visited and the mdw isn't aware of that transaction yet. this will basically displayed for almost everybody opening the explorer immediately after broadcasting a transaction:
![image](https://user-images.githubusercontent.com/8124114/136977179-881a4232-2958-4740-9e6b-47d49e9e1655.png)

to provide a more convenient UX here we should use the websocket connection of the mdw to update the page automatically if the tx appears.

additionally we should change the text displayed text like this:
- "Transaction not found. If you have sent it only a short time ago, please give the network some time to sync. You don't need to refresh this page. The transaction will automatically be displayed as soon as it's found."

**Comment by marc0olo** [comment]
@thepiwo it seems we cannot use websocket to achieve that kind of behavior. @AtanasKrondev informed me that it is **very** likely that the mdw backend has already notified subscriptions when the tx detailview of the frontend is openend. so in case we subscribe after that happened we will never be informed about this tx.

currently I think the only option we have here is polling

**Comment by marc0olo** [comment]
There is some special behavior that needs to be considered because the middleware is always 1 keyblock behind. As long this is the case we should also fetch tx information from the node to let the user know the tx really exists and that it is just not indexed yet.

This is very important IMO.

**Comment by thepiwo** [comment]
yes, I agree

**Comment by ifaouibadi** [comment]
I think we should display a progress indicator based on time (now() - last block. time) since we know how much it will take for the new block to be available

**Comment by marc0olo** [comment]
> I think we should display a progress indicator based on time (now() - last block. time) since we know how much it will take for the new block to be available

the time between block generation varies. this is not fixed "3 minutes". IMO we should just have different states for the transaction:

- unknown (not seen on the node, ever)
- pending (in mempool but not included in microblock yet)
- mined (included in microblock)
- mined & synced (in microblock and indexed by mdw)

I am not sure right now if we can show "pending" as I think this is a debug endpoint of the node. for the moment we could leave "pending" out.

if the tx is "mined" but not yet indexed by mdw we won't be able to display all the data which will become available after indexing is done.

not sure actually how to deal with that and what data would be missing. maybe we should display "awaiting indexing" or so for these fields.

from logical point of view I see the following order:

- try to fetch tx-info from middleware
    - SUCCESS => DONE
    - FAILS
         - subscribe to WS event and await indexation of the tx
         - fetch information from node to display "unknown" / ("pending") / "mined"
         - update view after indexation is done => DONE

what do you think @ifaouibadi @thepiwo ?

**Comment by thepiwo** [comment]
sounds very good to me
