### ISSUE TITLE
inconvenient ux for showing transactions (dashboard vs transactions route)

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#106]
for #93 I am wondering. it seems like transactions aren't being updated when switching pages. for example I see a new generation which already includes transactions but when moving back to the transaction page those new transactions aren't displayed

_Originally posted by @marc0olo in https://github.com/aeternity/mdw-frontend/issues/95#issuecomment-932099316_

---------------------------

read the whole history of https://github.com/aeternity/mdw-frontend/pull/95 to get more background information here.

it seems like currently there is no convenient way to make the latest transactions accesible in the `/transactions` route. as the latest transactions in the dashboard are updated via websocket connection the user might get the feeling that some txs are gone.

for me personally this was and still is very confusing

**Comment by marc0olo** [comment]
> @AtanasKrondev I agree, not mix the results from websocket and http, but we can use the websocket as ping to fetch new transactions. On the home page the goal is to get a quick moving feeling right, I guess there we need the websocket results to achieve that.

we are exactly doing that and it confuses me as user incredibly when switching to the `transactions` in the menu because suddenly I don't see the transactions anymore which have been displayed in the dashboard. they are basically all missing in that view.

personally I am not sure if we should even display this. maybe in a separate menu entry "real-time transactions" or sth. like that. completely remove it from dashboard or so.

**Comment by AtanasKrondev** [comment]
Definitely we shouldn't scrape this view. It's working fine, but it's not well explained what the user should expect from it.
Renaming or/and explanation text should be the way to go.
How about increasing the number of transactions shown in the dashboard to 10 even 20? Sometimes is really easy to lose certain transaction, because in the next second a few new transactions appear on top.

**Comment by thepiwo** [comment]
@marc0olo @AtanasKrondev this will be included in our next release, but keep in mind that the mdw only indexed key-block by key-block for now

**Comment by thepiwo** [comment]
example implementation in https://github.com/aeternity/mdw-frontend/pull/132

**Comment by marc0olo** [comment]
@ifaouibadi I also put this into the todo list now as the new release is deployed now :-)
