### ISSUE TITLE
add missing data for `ContractCreateTx`

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#112]
What is missing from the contract create TX right now:
- method
- arguments
- return status
- gas used

_Originally posted by @AtanasKrondev in https://github.com/aeternity/mdw-frontend/issues/66#issuecomment-951865332_

we are waiting for https://github.com/aeternity/ae_mdw/issues/266 to be fixed in order to tackle this issue

**Comment by marc0olo** [comment]
there are some inconsistencies in the responses for `ContractCreateTx` and `ContractCallTx`.

also the `return_value` needs to be decoded via SDK in the ContractCreateTx instead of getting it delivered already decoded as `return` like in the ContractCreateTx

`return_value` for returning a `state` record is an empty string (`cb_Xfbg4g==`). that might be a bug in the core protocol

**Comment by marc0olo** [comment]
update:
- after consulting with Hans the `return_value` for the `return_type` "ok" is always empty, the initial state is never returned
- the `return_value` this is only relevant if the `return_type` is "error" meaning that the contract deployment failed. of course it needs to be decoded then here, too

**Comment by marc0olo** [comment]
@ifaouibadi I think the only two things we need to show in explorer for `ContractCreateTx` then are:
- `args` (which is `arguments` in the response of a `ContractCallTx`)
- `gas_used` (I think I saw that already being displayed in the explorer)

so probably we only need to add `args`.

we should make sure that we also correctly display failed contract deployments and handle the errors accordingly.

**Comment by marc0olo** [comment]
> we should make sure that we also correctly display failed contract deployments and handle the errors accordingly.

@ifaouibadi can you verify this please and confirm we show the message correctly? if you don't know how to achieve such a failed tx please ask in group chat for somebody to help

**Comment by ifaouibadi** [comment]
@marc0olo  confirmed & updated, now we're using the same error helper for displaying error messages
![4C8495C4-8FF6-455F-B07A-65F91FC72A76](https://user-images.githubusercontent.com/10424827/149711198-9d0c30e0-2bbd-4d10-9763-9b744a00be1b.png)

**Comment by marc0olo** [comment]
> @marc0olo confirmed & updated, now we're using the same error helper for displaying error messages

no I meant for failed contract deployments. the error messages there.

example way to reproduce and test (you can also ask in chat):

- Deploy a contract and make sure some condition is wrong (either logically in the `init` function by passing a wrong parameter or for example by providing a too low amount of `gas` to the transaction)
      - The transaction will go through but no contract will be deployed
- You will still be able to see the transaction in the explorer after a new keyblock / generation but it should be displayed with an error and the correct error message

Our toolchain normally prevents failed contract deployments because the SDK e.g. performs a `dry-run` before actually broadcasting the transaction as far as I know.

Anyway, I can provide you the following example to verify this:

- https://explorer.testnet.aeternity.io/transactions/th_5fBC2L6iugGst8Jh2DHZPYuheFWgWpBSGEuDL6vnBQDRdZzcQ

This transaction was reverted due to an invalid parameter in the `init` function. We should be able to see the error message in the explorer.

@ifaouibadi can you verify this?

**Comment by ifaouibadi** [comment]
we already have a field that show that this transaction been reverted 
![07FF291C-344F-4805-8785-D63F71365045](https://user-images.githubusercontent.com/10424827/149762831-2a23e393-ec0c-4b6b-a8aa-60ef203c93ab.png)

**Comment by marc0olo** [comment]
@ifaouibadi here an example for what I mean compared to a reverted `ContractCallTx`: https://explorer.testnet.aeternity.io/transactions/th_t288pCRpvb9CGjctdqRNCKdiMAaJKo5Yia8RQ9WqWkdue4rNi

![image](https://user-images.githubusercontent.com/8124114/149766053-2c047656-aef3-431f-bba1-dce15498ff12.png)

I mean actually the (decoded) reason for the return.

in the contract create tx previously mentioned above it should be: `Value must be greater than 10`

we should also display that here for the `ContractCreateTx`

**Comment by marc0olo** [comment]
ok I see "RETURN" currently shows `bool: false` as value instead of the error message that I expected (`Value must be greater than 10`)

@ifaouibadi can we move discussions about work in PR into the respective PR in the future? it's confusing for me to comment in the issue about PR related stuff.

I will approve the PR for the moment and create a new issue for the investigation with return value. maybe we cannot get a clear error message from the middlware (or node) in that regards right now

**Comment by marc0olo** [comment]
closed with #143
