### ISSUE TITLE
display internal transactions (function calls)

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#113]
- internal transactions (Chain.spend)

naming in the mdw for this is "function calls" as they are function calls inside of sophia indexed. For a single transaction, e.g. https://mainnet.aeternity.io/mdw/contracts/calls/txi/27393918 it shows the `function`, and details of the `internal_tx` indexed. (docs: https://github.com/aeternity/ae_mdw#function-calls) All internal functions that represent common transaction types wrapped inside function calls are indexed here, e.g. Chain.spend, Call.amount, Oracle.query and more

_Originally posted by @thepiwo in https://github.com/aeternity/mdw-frontend/issues/44#issuecomment-952670153_

**Comment by marc0olo** [comment]
https://mainnet.aeternity.io/mdw/contracts/calls/forward?function=Oracle&limit=1

**Comment by marc0olo** [comment]
https://mainnet.aeternity.io/mdw/contracts/calls/forward?function=Chain&limit=1

**Comment by marc0olo** [comment]
https://mainnet.aeternity.io/mdw/contracts/calls/forward?function=Call&limit=1

**Comment by marc0olo** [comment]
@thepiwo @sborrazas @jyeshe do we somehow have a full list of all possible "function calls" that could be displayed as internal transaction?

**Comment by sborrazas** [comment]
@marc0olo we do not, these function call names come directly from the core and we just treat them as regular strings, so they could be anything. 

Right now on our database we have the following internal calls, each with the number of times in which it was called:
```elixir
%{
  "AENS.transfer" => 12,
  "AENS.update" => 4,
  "Call.amount" => 7050,
  "Chain.spend" => 6343,
  "Oracle.query" => 36179,
  "Oracle.respond" => 62
}
```

**Comment by marc0olo** [comment]
thanks @sborrazas ! =)

@AtanasKrondev I think that should be sufficient information here :-)

**Comment by marc0olo** [comment]
@AtanasKrondev it seems like `Call.amount` is the amount a contract receives in a `ContractCallTx`. this should probably also reflect the `amount` to be seen in a `ContractCallTx`. I am currently not 100% sure if it's only about remote contract calls or also the general contract call.
