### ISSUE TITLE
introduce dedicated page for AEX-9 tokens

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#119]
I think we should introduce a dedicated route for AEX-9 tokens where we link to and where token details are displayed:
- contract id
- supply
- decimals
- transfers
- other data that the mdw endpoint provides for each AEX-9 token.

in best case we have an endpoint to get the token distribution. sth. similar to what etherscan provides. we should open a new issue for that of course. @AtanasKrondev can make a proposal what and how to display? if we miss important info from mdw please let me and @thepiwo know.

example:
- https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#balances

anyway, I think the token balance display for the very low amount of tokens needs to be fixed.

**Comment by AtanasKrondev** [comment]
Currently we can display a list of all existing tokens, showing ``contract_id``, ``decimals``, ``name`` and ``symbol``.
When clicking on an item it can lead to dedicated page for this token/contract.
There we can show all owners and their balances using [this](https://mainnet.aeternity.io/mdw/aex9/balances/ct_pqfbS94uUpE8reSwgtaAy5odGi7cPRMAxbjMyEzpTGqwTWyn5) endpoint.
We can also display all the transactions that are already available on ``.../contracts/transactions/ct_pqfbS94uUpE8reSwgtaAy5odGi7cPRMAxbjMyEzpTGqwTWyn5`` in similar fashion as on etherscan. Meaning a single row, consisting of tx hash, method, timestamp, sender and receiver.

What I couldn't find is an endpoint showing the ``supply`` of a certain token. @thepiwo, @marc0olo could you assist here?

**Comment by marc0olo** [comment]
> We can also display all the transactions that are already available on `.../contracts/transactions/ct_pqfbS94uUpE8reSwgtaAy5odGi7cPRMAxbjMyEzpTGqwTWyn5` in similar fashion as on etherscan. Meaning a single row, consisting of tx hash, method, timestamp, sender and receiver.

I am not sure if we should mix up the contract detail page with the token detail page. probably we are a bit better off if we distinguish. I think at some point we will need a redesign of the whole explorer anyway. but that's to be discussed. currently we should just show as much infos as convenient as currently possible.

> What I couldn't find is an endpoint showing the `supply` of a certain token. @thepiwo, @marc0olo could you assist here?

`total_supply` is a stateful entrypoint of each AEX-9 token contract. what we could to is call this endpoint for each contract. but generally I think it would be better to fetch that information from mdw.

what you could do is call this endpoint:
- https://github.com/aeternity/ae_mdw#aex9-contract-balances-1
    - example: https://mainnet.aeternity.io/mdw/aex9/balances/ct_pqfbS94uUpE8reSwgtaAy5odGi7cPRMAxbjMyEzpTGqwTWyn5

and calculate the sum of all account balances. not sure how inefficient this can be if the amount of holders becomes too big. for the moment it would probably be fine.

@thepiwo what do you think?

**Comment by thepiwo** [comment]
I think it should definetly be a separate page. The normal contract page should only contain normal contract information and show everything as it would be any other contract, plus maybe show a button if it is an AEX-9 contract to go to the separate page.

The separate page could then show all token holders and token transfers of that token with a AEX-9 related frontend.

> and calculate the sum of all account balances
thats `total_supply()`, can be fetched directly from the contract, which is not a `stateful entrypoint`

Maybe to just give a refresher on what the mdw is for, it is there to index information that is otherwise not queryable in a simple way. Its not supposed to proxy all data.

**Comment by marc0olo** [comment]
> thats `total_supply()`, can be fetched directly from the contract, which is not a `stateful entrypoint`

oh yes, not sure what I was talking about there 😅  - of course we should get the total_supply directly from the contract then @AtanasKrondev
