### ISSUE TITLE
display return value if `ContractCreateTx` reverts

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#147]
ok I see "RETURN" currently shows `bool: false` as value instead of the error message that I expected (`Value must be greater than 10`)

@ifaouibadi can we move discussions about work in PR into the respective PR in the future? it's confusing for me to comment in the issue about PR related stuff.

I will approve the PR for the moment and create a new issue for the investigation with return value. maybe we cannot get a clear error message from the middlware (or node) in that regards right now

_Originally posted by @marc0olo in https://github.com/aeternity/mdw-frontend/issues/112#issuecomment-1015861002_

**Comment by marc0olo** [comment]
the expected error message refers to following tx:

- https://explorer.testnet.aeternity.io/transactions/th_5fBC2L6iugGst8Jh2DHZPYuheFWgWpBSGEuDL6vnBQDRdZzcQ

**Comment by ifaouibadi** [comment]
We're not getting the error message from the mdw

![BDF4A31F-34D9-421C-A368-035603E34C48](https://user-images.githubusercontent.com/10424827/150730631-e0dce715-7e35-487d-b0e1-c33cd763ef05.png)

**Comment by marc0olo** [comment]
yes, let's put that on hold, this is more a discussion topic. sorry that I placed it under "TODOs"

**Comment by hanssv** [comment]
Apart from the "lets paste important data as a picture"...

```
(aeternity_ct@localhost)8> {contract_bytearray, RevertMsg} = aeser_api_encoder:decode(<<"cb_dVZhbHVlIG11c3QgYmUgZ3JlYXRlciB0aGFuIDEwylhteg==">>).
{contract_bytearray,<<"uValue must be greater than 10">>}
(aeternity_ct@localhost)9> aeb_fate_encoding:deserialize(RevertMsg).                                                                             
<<"Value must be greater than 10">>
```

@marc0olo Revert messages are available - you are confusing things with errors maybe?!

**Comment by marc0olo** [comment]
> Apart from the "lets paste important data as a picture"...

sorry 😅 

@hanssv yeah might be, got a lot confused when we discussed the stuff lately.

@ifaouibadi ok as you can see the return value can be decoded. if you need help in that regards please ask anybody in the chat.

putting it back to "to do"
