### ISSUE TITLE
info about wrap / unwrap of AE in DEX contract

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#150]
we should display DEX related contract calls for wrap / unwrap of AE the same way like we do it for token transfers and change allowance already.

@kenodressel @bogdan-manole what functions are executing that logic? or is this done under the hood in other entrypoints? can / do we need to explicitly display those activities?

**Comment by bogdan-manole** [comment]
Don't know what we have to do , but I can explain what's in the Router:
all entrypoints that have AE in the naming have only one token as parameter and for the other one is using WAE under the hood to complete the action. Also is expecting to receive AE to the router address (eg:`add_liquidity_ae`) or AE will be received into the wallet of the caller (eg: `remove_liquidity_ae`) both depending on the nature of the entrypoint

**Comment by marc0olo** [comment]
closing this for now

**Comment by bogdan-manole** [comment]
The Pool does not know anything about the AE. The Router is the one who deals with AE be sent into the WAE contract, or getting out AE from the WAE address .

**Comment by marc0olo** [comment]
here it's just about what we wanna display in the explorer. if I see we need it I will open the issue again
