### ISSUE TITLE
error-handling on account page: `o.map is not a function`

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#168]
![image](https://user-images.githubusercontent.com/8124114/154056457-38b18029-a320-4b4c-be68-a431582ad6f9.png)

in the `v1.5.0` of the mdw backend we get an internal server error which produces this output.

we should handle this and give the user a hint to provide an issue.

everything else except AEX-9 balances should be displayed correctly

example account used in screenshot:
- https://explorer.testnet.aeternity.io/account/ak_2UGL6qArnbWx9fEkJyszssMkCjpu3VeLFBPA6MXYV3APfDSz1k

**Comment by ifaouibadi** [comment]
This is a known error in the current mdw version

https://testnet.aeternity.io/mdw/aex9/balances/account/ak_2UGL6qArnbWx9fEkJyszssMkCjpu3VeLFBPA6MXYV3APfDSz1k

fixed in 
https://testnet.aeternity.art/mdw/aex9/balances/account/ak_2UGL6qArnbWx9fEkJyszssMkCjpu3VeLFBPA6MXYV3APfDSz1k

**Comment by marc0olo** [comment]
I am aware of that. But the frontend needs to handle this. It only affects the AEX-9 balance and a typical visitor of this page should still be able to see the rest.

Technical errors like this should never touch the UI.

**Comment by marc0olo** [comment]
closes with #169
