### ISSUE TITLE
Show balance at account page

### ISSUE THREAD

**Issue by mradkov** [aeternity/mdw-frontend#28]
Lets display somewhere the final balance of account on the account page: https://explorer.aeternity.io/account/transactions/ak_wTPFpksUJFjjntonTvwK4LJvDw11DPma7kZBneKbumb8yPeFq

**Comment by marc0olo** [comment]
maybe we can also show additional information about the account in general. the account can be either **basic** or **generalized**

in case of a generalized account there is a contract attached to it, see:
- https://mainnet.aeternity.io/v3/accounts/ak_2RUVa9bvHUD8wYSrvixRjy9LonA9L29wRvwDfQ4y37ysMKjgdQ

should I open a separate issue for that @AtanasKrondev ?
