### ISSUE TITLE
Properly display auction bids

### ISSUE THREAD

**Issue by cytadela8** [aeternity/mdw-frontend#57]
Currently everything is shown as having max bid 5 aetos.

**Comment by cytadela8** [comment]
![image](https://user-images.githubusercontent.com/3736271/112306711-0020cf80-8c98-11eb-88b9-3a14b477ce47.png)

**Comment by marc0olo** [comment]
not an issue anymore. though I am wondering why "Max Bid" and the Name Length cannot be selected anymore :D
