### ISSUE TITLE
Sometimes the explorer connects to a server with an expired certificate

### ISSUE THREAD

**Issue by gorbak25** [aeternity/mdw-frontend#64]
![image](https://user-images.githubusercontent.com/1352848/112402626-2765b400-8d0d-11eb-8334-c6f8a8710980.png)

**Comment by mradkov** [comment]
Why do you use `aeternal.io`? Please use `explorer.aeternity.io` instead.

**Comment by davidyuk** [comment]
Probably this issue is on AE Studio side 😄
