### ISSUE TITLE
ContractCallTx display lacks basic information

### ISSUE THREAD

**Issue by gorbak25** [aeternity/mdw-frontend#65]
![image](https://user-images.githubusercontent.com/1352848/112564814-3bc4b200-8ddc-11eb-9307-e189ae337771.png)
1. What is the encoded calldata?
2. What is the decoded calldata?
3. What was the result of the call?
4. Did the call succeed or fail?
5. What events were emitted during execution?
6. What internal events occurred(Chain.transfer, etc...)?
7. How much GAS did my transaction use up...
etc...

**Comment by AtanasKrondev** [comment]
So we get quite of information from the mdw. For example:
```
{
  "block_hash": "mh_Tkkww5xu113So1YtkpM6NoHGfYCDrteJTbGVAF2pdkKjQC5Xj",
  "block_height": 444828,
  "hash": "th_HyZ1KwaAsLb4psMAoHWjGsz32wSSYh421TkNJBHzvXdjzZ8s9",
  "micro_index": 3,
  "micro_time": 1623931481469,
  "signatures": [
    "sg_DuMhs2i3hzroSZYUFU4CDXza5QN3ekzVKLKvmdZLeBFqN1uQTp8yJCBZqMrhvaaivcfYKngn5dVQ5MsQVmSdAUxoimv8j"
  ],
  "tx": {
    "abi_version": 3,
    "amount": 0,
    "arguments": [
      {
        "type": "string",
        "value": "Just a reminder...#love"
      },
      {
        "type": "list",
        "value": [
          {
            "type": "string",
            "value": "https://media1.giphy.com/media/jRlP4zbERYW5HoCLvX/giphy.gif?cid=685697e51zz6kjxs86v2hvle9w05l3qufhpk34q8ezb21qcz&rid=giphy.gif&ct=g"
          }
        ]
      }
    ],
    "call_data": "cb_KxEcOXhiK11KdXN0IGEgcmVtaW5kZXIuLi4jbG92ZRMBbwNodHRwczovL21lZGlhMS5naXBoeS5jb20vbWVkaWEvalJsUDR6YkVSWVc1SG9DTHZYL2dpcGh5LmdpZj9jaWQ9Njg1Njk3ZTUxeno2a2p4czg2djJodmxlOXcwNWwzcXVmaHBrMzRxOGV6YjIxcWN6JnJpZD1naXBoeS5naWYmY3Q9Z6NqwcY=",
    "caller_id": "ak_psgfxY4VcnJBTTshx2amBFf397ryoPKTTXyAcrx7BxVAVbt1W",
    "contract_id": "ct_2Hyt9ZxzXra5NAzhePkRsDPDWppoatVD7CtHnUoHVbuehwR8Nb",
    "fee": 185220000000000,
    "function": "post_without_tip",
    "gas": 1579000,
    "gas_price": 1000000000,
    "gas_used": 5430,
    "log": [
      {
        "address": "ct_2Hyt9ZxzXra5NAzhePkRsDPDWppoatVD7CtHnUoHVbuehwR8Nb",
        "data": "cb_SnVzdCBhIHJlbWluZGVyLi4uI2xvdmXhLZdu",
        "topics": [
          "83408474105809356723083641835082858468110713825767194599189017517019994517159",
          "49167971719193715951266994076287065871368293531963363040300456373733597204057"
        ]
      }
    ],
    "nonce": 39,
    "result": "ok",
    "return": {
      "type": "int",
      "value": 140
    },
    "return_type": "ok",
    "type": "ContractCallTx",
    "version": 1
  },
  "tx_index": 23233360
}
```

Let's think what part of this will be useful and how to present it.

**Comment by marc0olo** [comment]
I think we should definitely display following information:
- function-name
- arguments
- rename `gas` to `gas limit` to avoid confusion
- gas used (very important)
- status (we already have that now if https://github.com/aeternity/mdw-frontend/pull/98 is merged)
- return type and value (can be empty of course)

I would also like to display the events. but this can be handled in a different issue IMO

**Comment by marc0olo** [comment]
@AtanasKrondev just to provide some clarity about the total costs for the transaction from user perspective we might add a separate display for that which is named and calculated as follows:
- Total costs (gas + fee): `gas used` * `gas price` + `fee`
