### ISSUE TITLE
Show amount of confirmations in transactions details

### ISSUE THREAD

**Issue by davidyuk** [aeternity/mdw-frontend#71]
https://explorer.aeternity.io/transactions/th_d7Hww5RFtYp2M6vM9VSF5qPTM3WMQjqM5Va2Lrtv9ht2LSeoB

currently, it shows only the block height

**Comment by marc0olo** [comment]
currently discussing with @AtanasKrondev regarding amount of confirmations. how should we display that? I mean we have 3 different states IMO:
- "chosen by leader"
- "included in keyblock of following leader"
- "included in keyblock of following leader +1"

any proposals how to display that? let's also check how AEknow is handling that at the moment
