### ISSUE TITLE
Functionless "load more" button

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/mdw-frontend#85]
Hey, I noticed that the "load more" button below the TX details here doesn't do anything: https://explorer.mainnet.aeternity.io/contracts/transactions/ct_2rfqVEQc3uTmLskb6CKfQKF1ytyGddfwxb6awSRySPMJ7TWuh1

**Comment by marc0olo** [comment]
@AtanasKrondev you told me about that recently, too. right? is there already an issue for that? do you know what's the problem? maybe this was related to mdw-backend. then we should discuss this with the mdw devs. maybe it has already been fixed then

**Comment by AtanasKrondev** [comment]
Actually it does. Every click sends a request and receives ``[]`` as response but the UI doesn't indicates it in any way.

commit fc2bb48990b1d4ff7e31ae1273c5f51492d4d35c should fix it.
