### ISSUE TITLE
State of tx is not displayed

### ISSUE THREAD

**Issue by kenodressel** [aeternity/mdw-frontend#89]
I made a couple aex9 token transfers but they are not displayed correctly:
1. (fine) https://explorer.aeternity.io/transactions/th_RG8LDuzDGqgU6YkAQQPgBzggxBfmuS4oLruaGqK552HsbPsEG
2. (broken) https://explorer.aeternity.io/transactions/th_hdsxFZMqNrV9ATQDvSBLQ9BTZXPU8N2pPKpvgQmH23ic6jeBb
3. (broken) https://explorer.aeternity.io/transactions/th_2NDYTTvzL2jBgECREaEdFxRA1AJvwedZ2wdrZYmzZtgEKEBL44

this is because the two latter transactions actually got aborted by the contract & reverted. There is no sign of this in the explorer. I would like to see reverted / aborted tx flagged, if they are listed at all...

**Comment by marc0olo** [comment]
@AtanasKrondev it would be good to have this handled directly after #80
