### ISSUE TITLE
display tokens and token-balances owned by an account

### ISSUE THREAD

**Issue by marc0olo** [aeternity/mdw-frontend#90]
we should display the tokens and the respective amount an account owns when accessing the account-details page.

I am currently just wondering what's the best way here. for accounts we currently always point to the URL `.../account/transactions/ak_wTPFpksUJFjjntonTvwK4LJvDw11DPma7kZBneKbumb8yPeFq` where explicitely "transactions" is included.

we should discuss the behavior here before implementing it accordingly

**Comment by AtanasKrondev** [comment]
We can do something like this
<img width="800" src="https://user-images.githubusercontent.com/47859124/139498538-55cf8eca-6f26-48cb-ac61-d0ce4d63ceb3.png">

Is there any particular reason to keep ``transactions`` in the URL? Can't we just drop it to``.../account/ak_wTPFpksUJFjjntonTvwK4LJvDw11DPma7kZBneKbumb8yPeFq``

**Comment by marc0olo** [comment]
> Is there any particular reason to keep `transactions` in the URL? Can't we just drop it to`.../account/ak_wTPFpksUJFjjntonTvwK4LJvDw11DPma7kZBneKbumb8yPeFq`

personally I also don't like this. if we switch we should make sure old routes aren't broken. either on proxy level or on implementation level. is it possible to define a permanent redirect on application level? does that make sense? never did that before 🤔

**Comment by marc0olo** [comment]
> We can do something like this
> <img alt="" width="800" src="https://user-images.githubusercontent.com/47859124/139498538-55cf8eca-6f26-48cb-ac61-d0ce4d63ceb3.png">

yeah I think we can go with that for the first shot :-)
